name: markdown-link-check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # upstream issue, https://github.com/tcort/markdown-link-check/issues/196
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          config-file: '.github/workflows/markdown.links.config.json'
