name: notfoundbot

on:
  push:
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
        with:
          fetch-depth: 0

      - name: Fix links
        uses: tmcw/notfoundbot@f91be597e4a7e2a182788b1c5ffdc460df3195ea # v2.3.1
        continue-on-error: true
        with:
          content-folder: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
