name: notfoundbot

on:
  push:
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Fix links
        uses: tmcw/notfoundbot@1f97e4c79fa3aeaa9b2b87b8cd2533f645fed82d # v3.0.0
        continue-on-error: true
        with:
          content-folder: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCEPTIONS: github.com developer.hashicorp.com www.hashicorp.com medium.com blog.pelo.tech terraformbook.com
